### PR TITLE
test erlang 21

### PR DESCRIPTION
**Pull request by getong**

### CODE REVIEW

**Comment by getong** [comment]
@paulo-ferraz-oliveira @Vagabond 
The [stacktrace_compat](https://github.com/g-andrade/stacktrace_compat) seems to not work with otp 21. See the https://github.com/g-andrade/stacktrace_compat/blob/master/.travis.yml
```
#    - 21.0 FIXME wait for Travis to get OTP 21 -compatible rebar3
```
And in hex.pm, the poolboy has 856403 downloads, it needs a new tag and push to hex.pm.
And this pr uses `OTP_RELEASE` and test otp 21, and the ci build result shows this pr works. 
I think this pr can be merged asap.
Feedback is welcome.

**Comment by fenollp** [comment]
Just wanted to say I like your stacktrace macros very much!
LGTM.

**Comment by getong** [comment]
@fenollp 
It is copied from [meck](https://github.com/eproxus/meck/blob/master/src/meck_code_gen.erl#L186-L192)

**Comment by paulo-ferraz-oliveira** [comment]
@getong: it does work with OTP 21 :D I've already deployed it to live systems with no issues. It was created for OTP 21 compatibility.

On the other hand, even if you don't consider it a good alternative (some might) it was recently merged into elli: https://github.com/elli-lib/elli/pull/61 (though I later figured out that it wasn't necessary, so removed it).

I also like your approach (though it involves macros and changing code+), I'm just saying that there's no **better approach** in this case.

+imagine you have a huge project with 20/30 try catch statements, while stacktrace_compat might use parse_transforms but it requires no change to existing code.

**Comment by g-andrade** [comment]
@getong 
> The stacktrace_compat seems to not work with otp 21.

It does work ;-). Test cases are passed and coverage is full. What's broken is the rebar3 version that's bundled with Travis, as mentioned in [this issue](https://github.com/travis-ci/travis-ci/issues/9830). I've [solved it](https://github.com/g-andrade/stacktrace_compat/commit/eee7a8154a2769a58475b1911715e01df2411702) by always downloading the latest rebar3 when running tests under Travis.

As for it being complex, well there's not much of a counterargument I can offer - parse transforms are complex almost by definition, as they manipulate code in the [abstract format](http://erlang.org/doc/apps/erts/absform.html). But I wouldn't expect it to be particularly hard to maintain; there isn't anything else to be done on features at this point.

**Comment by getong** [comment]
@Vagabond 
Would you spend some time merging this code?

**Comment by Vagabond** [comment]
Alright I merged this and fixed the dialyzer specs.

**Comment by Vagabond** [comment]
I tagged 1.5.2 but I can't push to hex. @devinus can you grant me access?

**Pull request merged**
