### PR TITLE
Add ability to remove overflow workers after a delay

### PR DESCRIPTION
**Pull request by zugolosian**
Hi,

I'm aware you've rejected similar proposals in the past, but my use case is slightly different. Here goes:

We're using poolboy to pool python workers in combination with erports. The reason for this is we write software that manages network attached storage. When network attached storage becomes unresponsive as it does from time to time you need to kill the process for the kernel to clean up properly. The reason we chose python workers is their path manipulation libraries are very good amongst other things 

When load testing with poolboy we found that as soon as the pool went into overflow cpu on the machine went through the roof because of high worker churn. Having our workers start in an unconnected state isn't as useful as having a pool that optionally keeps workers around for a while under peak load because starting python workers is always expensive. Which means in order to provide good latency when not under load we'd have to either dynamically spin up small non-overflow pools or something. Also we run more than one type of worker on our servers and implementing the "disconnected" logic in many places when it could just be done in one seemed a bit silly.

I'm interested in hearing your thoughts on this.

Thanks

### CODE REVIEW

**Comment by kevinbombadil** [comment]
+1

**Comment by yjh0502** [comment]
+1 poolboy behaves badly when spawning/killing new workers is rather expansive. I'm using poolboy with pgapp[1], and erlang node become unstable when pool overflows.

[1] https://github.com/epgsql/pgapp

**Comment by zugolosian** [comment]
@yjh0502 I'd be interested to know if the fork I made works for your use case.

**Comment by davidw** [comment]
I don't work with Erlang any longer (sadly), but would happily switch epgsql to use a fork of poolboy that handles things this way if it's something that gets maintained long term.

**Comment by devinus** [comment]
I'm going to branch off of this and with some improvements merge it.

**Comment by zugolosian** [comment]
Awesome, thanks!

**Comment by devinus** [comment]
@zugolosian I've been giving this a lot of review and I'm not sure the logic is quite right. Could you walk me through some of it?

I'm specifically worried about: https://github.com/devinus/poolboy/pull/83/files#diff-96c7a4d851dcecda493caf816793b18fR360

Why does the overflow stay the same here: https://github.com/devinus/poolboy/pull/83/files#diff-96c7a4d851dcecda493caf816793b18fR365

**Comment by zugolosian** [comment]
For this one:
https://github.com/devinus/poolboy/pull/83/files#diff-96c7a4d851dcecda493caf816793b18fR360

Let's look at the simplest case, from simplest to most complicated flow. 

When we're not in overflow ie. We've got 1 worker checked out or less we'll hit this clause:
`{empty, Empty} ->` 
And proceed as usual.

When we're in overflow but we haven't set an overflow ttl we'll hit this clause
`{empty, Empty} when Overflow > 0 ->`
And proceed as usual

When we're in overflow and we have set an overflow ttl it starts to get interesting:
`{empty, Empty} when Overflow > 0, OverflowTtl > 0 ->`
* First we check if the worker we've been asked to check in, is already in the table of workers to be removed after a delay. 
 * If it's not already in the table we start a timer, grab the Tref and add it to the table. We don't decrement the overflow counter YET because it's not actually gone yet, we're still in a state of overflow but the worker is ready for immediate use. 
 * If it is already in the table it's been used since the timer was set and we need to cancel the timer and add the new timer to the table by inserting/overwriting the old entry. The overflow should still not be decremented in the case we already have the worker in the table, this is an error on my part. The overflow is decremented when the worker is stopped.

It should look more like:
```
         {empty, Empty} when Overflow > 0, OverflowTtl > 0 ->
             case ets:lookup(WorkersToReap, Pid) of
                 [] ->
                     {ok, Tref} =
                         timer:send_after(OverflowTtl, self(), {reap_worker, Pid});
                 [{Pid, Tref}] ->
                     {ok, cancel} = timer:cancel(Tref),
                     {ok, Tref} =
                         timer:send_after(OverflowTtl, self(), {reap_worker, Pid})
             end,
             true = ets:insert(WorkersToReap, {Pid, Tref}),
             Workers = case Strategy of
                           lifo -> [Pid | State#state.workers];
                           fifo -> State#state.workers ++ [Pid]
                       end,
             State#state{workers = Workers, waiting = Empty};
```
A test should also be added for this which I'm happy to do if you'd like. Feel free to let me know if you have any more questions or if I'm wrong about something.

**Comment by devinus** [comment]
@zugolosian To sort of walk thru scenarios:

- Checkout happens and overflow TTL exists, unset any timer before returning worker
- Checkin happens and overflow TTL exists and we're in overflow but beyond max overflow, the worker should be dropped
- Checkin happens and overflow TTL exists and we're not beyond max overflow, the timer should be set, overflow increased, and worker returned to pool

**Comment by zugolosian** [comment]
@devinus  To sort of walk thru scenarios:

`* Checkout happens and overflow TTL exists, unset any timer before returning worker`
Correct
`* Checkin happens and overflow TTL exists and we're in overflow but beyond max overflow, the worker should be dropped`
We should never be in a state where we're beyond max overflow, the logic in the checkouts doesn't allow that to happen
`* Checkin happens and overflow TTL exists and we're not beyond max overflow, the timer should be set, overflow increased, and worker returned to pool`
Overflow is only increased when an overflow worker has been started as part of the checkout. We're not starting any extra workers. For example:
 * We've got a pool size of 1 a max_overflow of 1 and an overflow_ttl of 300 milliseconds
 * We checkout a worker, overflow is  zero
 * We checkout another, overflow is now 1
 * We checkin a worker. We start an erlang:send_after to schedule the worker to be reaped in 300 milliseconds. It is added back to the pool of workers and overflow is *not* touched. It is still set to 1.
  * If someone attempts a checkout within 300 milliseconds they will get the worker that's in the pool and the timer will be canceled. When the worker is checked in again a new timer is started.
  * If no one attempts a checkout within 300 milliseconds the worker will be dropped and *only then* will the overflow number be decreased

**Comment by zugolosian** [comment]
@devinus Let me know if you have any further questions.

Cheers

**Comment by zugolosian** [comment]
FYI, we've been running the above fork in production for 2 months now without issue.

**Comment by comtihon** [comment]
@zugolosian is it efficient to start and cancel timer on every overflow worker checkout?
I mean - under heavy load overflow worker can process lots of requests, going one by one. So there will be lot of unneeded timer creation and cancelling.  
May be it is better to remember last time of use for overflow worker and kill old unused workers by some per second timer check?

**Comment by zugolosian** [comment]
@comtihon

That's a good idea, I never even considered it. 

I think in most cases people using ttl will be connecting to an external resource and the cost of starting and stopping a timer won't be significant. Another thing is that if you reap workers at an interval you're immediately limiting the granularity of your ttl to the reap interval which you'd have to expose the user to. 

I also suspect if you have a large number of overflow workers you could get into a state where poolboy spends all its time reaping. I don't know how efficient it will be to check the age of all overflow workers at an interval vs waiting for timers to expire. A timer seems more like it will have more predictable behaviour to me.

Is there a use case where you see the timer implementation being a problem?

**Comment by comtihon** [comment]
@zugolosian @devinus 
I changed algorythm for more effective from my point of view.
As for reap workers interval - it is one second, or equal owerflow_ttl, as you can see https://github.com/zugolosian/poolboy/pull/1/commits/8f8f5fe67802acf0c8f1e80524b49d270cdbd12c#diff-96c7a4d851dcecda493caf816793b18fR144
This reduces limit granularity of ttl interval.

From my point of view it is much more efficient to process workers ttl in one call on large numbers. You see - in your case large number of workers spawn large number of timers, that sends large numbers of rip_worker messages to poolboy process. It can flood much.

As you can see from https://github.com/zugolosian/poolboy/pull/1/commits/8f8f5fe67802acf0c8f1e80524b49d270cdbd12c#diff-96c7a4d851dcecda493caf816793b18fR377
 I iterate only for idle workers and only by overflow number. So I consider this to be efficient.

Should I create PR to devinus/poolboy?
It is PR to zugolosian/poolboy `https://github.com/zugolosian/poolboy/pull/1`

**Pull request closed without merging**
