### PR TITLE
OTP 19 dialyzer + OTP 21 compilation issues

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**

### CODE REVIEW

**Comment by getong** [comment]
@paulo-ferraz-oliveira I think my pr #105 is better than yours, take a look at it.

**Comment by paulo-ferraz-oliveira** [comment]
@getong, do you mean #104? [_better_ is a relative term, I guess :D]

In any case, you didn't include:
+    supervisor :: undefined | pid(),
+    workers :: undefined | [pid()],
/https://github.com/devinus/poolboy/pull/105/files#diff-96c7a4d851dcecda493caf816793b18fR32)
in poolboy.erl, which means it won't dialyze without warnings in OTP 19, which was also one of the goals of this PR.

I'll close it since it seems nobody's paying attention to PRs anyway :D (the last change was 2 years ago and there's about 15 unanswered PRs).

**Comment by Vagabond** [comment]
If you want to add the extra versions to Travis for this PR and re-open it, I can merge it.

**Comment by Vagabond** [comment]
Actually, I'm not sure on the OTP compatability guidelines for poolboy, but surely we can drop R16 at this point?

**Comment by getong** [comment]
@Vagabond #104 test erlang version from 17 to 21, and all tests passed, I think you can merge that first. And a new tag need to be pushed to hex.pm.

**Pull request closed without merging**
